### ISSUE TITLE
Change "admin"/"password" account

### ISSUE THREAD

**Issue by MattiaCC93** [apromore/ApromoreCore#183]
Is it possible to change the password of the "admin" account? Alternatively, is it possible to disable it to prevent unauthorized access?

**Comment by verenich** [comment]
Yes, when you create and populate MySQL database, you can define users and their passwords in the [membership](https://github.com/apromore/ApromoreCore/blob/master/Supplements/database/db-mysql.sql#L913) table. You see, by default it is 5f4dcc3b5aa765d61d8327deb882cf99 for everyone, which is a hash for "password" (no quotes)

**Comment by MattiaCC93** [comment]
Thank you verenich!
