### ISSUE TITLE
testWriteCSV(cs.ut.ui.controllers.TrainingControllerUnitTest) <= FAILURE

### ISSUE THREAD

**Issue by sabatale** [apromore/ApromoreCore#211]
Hello,

I get the following error at step "Predictor training portal plugin 1.0" while compiling the Master.

It looks similar to [Issue #176](https://github.com/apromore/ApromoreCore/issues/176):

```
-------------------------------------------------------------------------------
Test set: cs.ut.ui.controllers.TrainingControllerUnitTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.464 sec <<< FAILURE!
testWriteCSV(cs.ut.ui.controllers.TrainingControllerUnitTest)  Time elapsed: 0.605 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...""four""","five
six"[]
> but was:<...""four""","five
six"[
]
>
	at org.junit.Assert.assertEquals(Assert.java:125)
	at kotlin.test.junit.JUnitAsserter.assertEquals(JUnitSupport.kt:27)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:59)
	at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
	at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:58)
	at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
	at cs.ut.ui.controllers.TrainingControllerUnitTest.testWriteCSV(TrainingControllerUnitTest.kt:93)
```

### **Environment**

**OS**
Windows 10 (Non-pro)

**java -version**
Picked up _JAVA_OPTIONS: -Xmx3G
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**mvn -v**
Picked up _JAVA_OPTIONS: -Xmx3G
Apache Maven 3.6.2
Java version: 1.8.0_221, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_221\jre
Default locale: en_CA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**ant -version**
Picked up _JAVA_OPTIONS: -Xmx3G
Apache Ant(TM) version 1.10.7 compiled on September 1 2019

Any idea?

Thanks!

**Comment by verenich** [comment]
indeed, you need to replace \n with \r\n to pass the test on Windows

**Comment by sabatale** [comment]
Indeed it did work. Thanks!

More precisely, for Windows users, add \r in front of the \n at the end of the following file: TrainingControllerUnitTest.kt.

```
  @Test
  fun testWriteCSV() : Unit {
       val values = Arrays.asList("one", "two,three", "\"four\"", "five\r\nsix")
       val outputStream = ByteArrayOutputStream()
       val printWriter = PrintWriter(outputStream)
       TrainingController.writeCSV(values, printWriter)
       printWriter.close()

       assertEquals("one,\"two,three\",\"\"\"four\"\"\",\"five\r\nsix\"\r\n", outputStream.toString())
  }
```
