### ISSUE TITLE
Import logs from CSV files functionality has no encoding option.

### ISSUE THREAD

**Issue by gntontos** [apromore/ApromoreCore#220]
Hi there
We installed Apromore version 7.10 for windows and the encoding option, as described in the url below, is missing. 
https://apromore.org/import-logs-from-csv-files/

Attached you can find a screenshot from our installation where the encoding option is missing.
![CSV_Importer](https://user-images.githubusercontent.com/32293953/71106179-857d2080-21c7-11ea-9682-570539e083a7.PNG)

**Comment by verenich** [comment]
Hi,
support for encodings has been added in the upcoming version 7.12. Please use the code https://github.com/apromore/ApromoreCore/tree/v7.12

**Comment by gntontos** [comment]
Thank you
I will try it tomorrow.

**Comment by gntontos** [comment]
Hi verenich,
Just to inform you that :)
CSVImporterLogicImplUnitTest is configured for utc+10 timezone.

I will change my server time to pass the tests.
