### ISSUE TITLE
BPMN Model with Greek characters.

### ISSUE THREAD

**Issue by gntontos** [apromore/ApromoreCore#222]
Hi there,
we are using Apromore 7.12 for Windows.
Our data contains Greek characters and when we try to save as BPMN Model from the process discoverer page we get the following error.

org.apromore.canoniser.exception.CanoniserException: Could not canonise BPMN 2.0

This only happens with data containing Greek characters.

Any suggestion?

**Comment by marlondumas** [comment]
Apromore EE 7.14 and 7.15 already support UTF-8. You can check the free trial version (90 days) here:  https://apromore.org/platform/cloud/
Apromore Community Edition (CE) 7.14 is coming up end of May.

**Comment by gntontos** [comment]
Thank you.
