### ISSUE TITLE
Maven error

### ISSUE THREAD

**Issue by ffalcolini** [apromore/ApromoreCore#226]
Hi!
The command `mvn clean install `returns an error.

[INFO] Reactor Summary:
[INFO]
[INFO] Apromore Build Tools Extension 1.1 ................. SUCCESS [  2.766 s]
[INFO] Apromore :: ui :: ui-theme-compact 1.0-SNAPSHOT .... SUCCESS [ 29.336 s]
[INFO] Apromore Testing Tools 1.1 ......................... SUCCESS [  1.168 s]
[INFO] Apromore 1.1 ....................................... SUCCESS [01:07 min]
[INFO] Apromore ANF Schema 1.1 ............................ FAILURE [  0.125 s]
[INFO] Apromore ARIS Schema 1.1 ........................... SKIPPED
[INFO] Apromore BPMN Schema 1.1 ........................... SKIPPED
[INFO] Synergia CMAP Schema 1.1 ........................... SKIPPED
[INFO] Apromore CPF Schema 1.1 ............................ SKIPPED
[INFO] Synergia DCL Schema 1.1 ............................ SKIPPED
[INFO] Apromore EPML Schema 1.1 ........................... SKIPPED
[INFO] Apromore PNML Schema 1.1 ........................... SKIPPED
[INFO] Apromore RLF Schema 1.1 ............................ SKIPPED
[INFO] Apromore XPDL Schema 1.1 ........................... SKIPPED
[INFO] Apromore YAWL Schema 1.1 ........................... SKIPPED
[INFO] jdom2-osgi 2.0.6 ................................... SKIPPED
[INFO] OpenXES 2.27 ....................................... SKIPPED
[INFO] log-osgi 1.1 ....................................... SKIPPED
[INFO] lpsolve-osgi 1.1 ................................... SKIPPED
[INFO] prom6-osgi 6.0 ..................................... SKIPPED
[INFO] eclipse-collections-osgi 1.1 ....................... SKIPPED
[INFO] antlr4-runtime-osgi 4.3 ............................ SKIPPED
[INFO] bpstruct-osgi 1.2 .................................. SKIPPED
[INFO] raffaeleconforti-osgi 1.1.1 ........................ SKIPPED
[INFO] bpmntk-osgi 2.1 .................................... SKIPPED
[INFO] json-osgi 20090211 ................................. SKIPPED
[INFO] jbpt-petri-osgi 0.2.433 ............................ SKIPPED
[INFO] eventstr-confchecking-osgi 1.1 ..................... SKIPPED
[INFO] pn-automata-conv-osgi 1.1 .......................... SKIPPED
[INFO] ltl-to-automaton-osgi 1.1 .......................... SKIPPED
[INFO] declare-visualizer-osgi 1.1 ........................ SKIPPED
[INFO] prom-pnml-osgi 1.1 ................................. SKIPPED
[INFO] ltl-conf-check-osgi 1.1 ............................ SKIPPED
[INFO] apm-verification-osgi 1.1 .......................... SKIPPED
[INFO] ini4j-osgi 0.5.2 ................................... SKIPPED
[INFO] postgresql-osgi 9.3-1101-jdbc41 .................... SKIPPED
[INFO] themis-osgi 1.0 .................................... SKIPPED
[INFO] lucene-osgi 5.3.0 .................................. SKIPPED
[INFO] pql-osgi 1.2 ....................................... SKIPPED
[INFO] prodrift-osgi 2.5 .................................. SKIPPED
[INFO] zk-osgi 8.6.0.1 .................................... SKIPPED
[INFO] Apromore Plugins 1.1 ............................... SKIPPED
[INFO] Apromore Canonical Graph Plugin 1.1 ................ SKIPPED
[INFO] similaritysearch-osgi 1.1 .......................... SKIPPED
[INFO] Apromore H2 Plugin 1.1 ............................. SKIPPED
[INFO] Apromore MySQL Plugin 1.1 .......................... SKIPPED
[INFO] Apromore Oracle Plugin 1.1 ......................... SKIPPED
[INFO] Apromore PostgreSQL Plugin 1.1 ..................... SKIPPED
[INFO] Apromore Plugin API 1.1 ............................ SKIPPED
[INFO] Apromore Plugin API Provider 1.1 ................... SKIPPED
[INFO] Apromore Canoniser API 1.1 ......................... SKIPPED
[INFO] Apromore Manager WS Models 1.1 ..................... SKIPPED
[INFO] Apromore Portal Plugin API 1.1 ..................... SKIPPED
[INFO] Apromore Manager Client 1.1 ........................ SKIPPED
[INFO] Apromore Editor Plugin API 1.1 ..................... SKIPPED
[INFO] Apromore Canoniser API Provider 1.1 ................ SKIPPED
[INFO] Apromore Annotation Pre Processor API 1.1 .......... SKIPPED
[INFO] Apromore Annotation Pre Processor API Provider 1.1 . SKIPPED
[INFO] Apromore Deployment Plugin API 1.1 ................. SKIPPED
[INFO] Apromore Deployment Plugin API Provider 1.1 ........ SKIPPED
[INFO] Apromore ARIS Canoniser 1.1 ........................ SKIPPED
[INFO] Apromore BPMN Canoniser 1.1 ........................ SKIPPED
[INFO] Apromore EPML Canoniser 1.1 ........................ SKIPPED
[INFO] Apromore PNML Canoniser 1.1 ........................ SKIPPED
[INFO] Apromore XPDL Canoniser 1.1 ........................ SKIPPED
[INFO] Apromore YAWL Canoniser 1.1 ........................ SKIPPED
[INFO] Apromore BPMN Annotation Pre Processor 1.1 ......... SKIPPED
[INFO] Apromore XPDL Annotation Pre Processor 1.1 ......... SKIPPED
[INFO] Apromore EPML Annotation Pre Processor 1.1 ......... SKIPPED
[INFO] Apromore YAWL Annotation Pre Processor 1.1 ......... SKIPPED
[INFO] Apromore PNML Annotation Pre Processor 1.1 ......... SKIPPED
[INFO] portal-custom-gui 1.1.0 ............................ SKIPPED
[INFO] Apromore File Store Client 1.1 ..................... SKIPPED
[INFO] Apromore Manager Security Handler 1.1 .............. SKIPPED
[INFO] Event log store service plugin API 1.1 ............. SKIPPED
[INFO] Process store service plugin API 1.1 ............... SKIPPED
[INFO] Log Filter Logic 1.0.0 ............................. SKIPPED
[INFO] The APMLogModule Project 0.1 ....................... SKIPPED
[INFO] Apromore Manager 1.1 ............................... SKIPPED
[INFO] Apromore Portal 1.1 ................................ SKIPPED
[INFO] YAWL Deployment Plugin 1.1 ......................... SKIPPED
[INFO] similaritysearch-logic 1.1.0 ....................... SKIPPED
[INFO] merge-logic 1.1.0 .................................. SKIPPED
[INFO] Example portal plugin 1.1 .......................... SKIPPED
[INFO] similaritysearch-portal 1.1.0 ...................... SKIPPED
[INFO] Merge portal plugin 1.1 ............................ SKIPPED
[INFO] Apromore Editor parent 1.2 ......................... SKIPPED
[INFO] Apromore Editor Extension: Diagram Core 1.2 ........ SKIPPED
[INFO] Apromore Editor Extension: BPMN 2.0 1.2 ............ SKIPPED
[INFO] BPMN diagram parser service (prom6) 1.1 ............ SKIPPED
[INFO] BEBoP service 1.1 .................................. SKIPPED
[INFO] Apromore Editor bebop plugin 1.1 ................... SKIPPED
[INFO] BProVe service 1.1 ................................. SKIPPED
[INFO] Apromore Editor bprove plugin 1.1 .................. SKIPPED
[INFO] Apromore Editor sample plugin 1.1 .................. SKIPPED
[INFO] iBPSruct service 1.1 ............................... SKIPPED
[INFO] Apromore Editor iBPStruct plugin 1.1 ............... SKIPPED
[INFO] Metrics service 1.1 ................................ SKIPPED
[INFO] Apromore Editor metrics plugin 1.1 ................. SKIPPED
[INFO] Apromore Editor metrics plugin 2 1.1 ............... SKIPPED
[INFO] Custom Plugin Framework 1.0.0 ...................... SKIPPED
[INFO] Log Management Logic 1.0.0 ......................... SKIPPED
[INFO] Log Filter Generic Portal Plugin 1.0.0 ............. SKIPPED
[INFO] Log Filter Portal Plugin 1.0.0 ..................... SKIPPED
[INFO] Account management portal plugin 1.0 ............... SKIPPED
[INFO] Apromore Portal Client 1.1 ......................... SKIPPED
[INFO] PQL query service 1.1 .............................. SKIPPED
[INFO] PQL Logic Web Services 1.1 ......................... SKIPPED
[INFO] apql 1.1 ........................................... SKIPPED
[INFO] APQL portal plugin 1.1 ............................. SKIPPED
[INFO] BEBoP portal plugin 1.1 ............................ SKIPPED
[INFO] BIMP-Annotation-logic 1.0 .......................... SKIPPED
[INFO] BIMP simulator editor plugin 1.0 ................... SKIPPED
[INFO] BIMP simulator editor plugin 1.0 ................... SKIPPED
[INFO] BIMP simulator portal plugin 1.0 ................... SKIPPED
[INFO] BPMNMiner-logic 1.1 ................................ SKIPPED
[INFO] Infrequent Behaviour Filter service 1.1 ............ SKIPPED
[INFO] BPMNMiner portal plugin 1.1 ........................ SKIPPED
[INFO] BPMN configurator 1.1 .............................. SKIPPED
[INFO] Cmapper 2.0 ........................................ SKIPPED
[INFO] Cmapper portal plugin 1.1 .......................... SKIPPED
[INFO] Compare service 1.1 ................................ SKIPPED
[INFO] Compare portal plugin 1.1 .......................... SKIPPED
[INFO] Compare portal plugin 2 1.1 ........................ SKIPPED
[INFO] CSVImporter-Logic 1.0 .............................. SKIPPED
[INFO] CSVImporter Portal 1.0 ............................. SKIPPED
[INFO] LTL conformance checking logic 1.1 ................. SKIPPED
[INFO] LTL Conformance portal plugin 1.1 .................. SKIPPED
[INFO] APM service 1.1 .................................... SKIPPED
[INFO] APM portal plugin 1.1 .............................. SKIPPED
[INFO] APM compliance service 1.1 ......................... SKIPPED
[INFO] APM compliance portal plugin 1.1 ................... SKIPPED
[INFO] APM compliance with guards logic 1.1 ............... SKIPPED
[INFO] APM compliance with transition guards portal plugin 1.1 SKIPPED
[INFO] iBPStruct portal plugin 1.1 ........................ SKIPPED
[INFO] Activity Filter Logic 1.1 .......................... SKIPPED
[INFO] Activity Filter portal plugin 1.1 .................. SKIPPED
[INFO] Infrequent Behaviour Filter portal plugin 1.1 ...... SKIPPED
[INFO] Log Animation service 1.0 .......................... SKIPPED
[INFO] Log Animation portal plugin 1.0 .................... SKIPPED
[INFO] Log Animation portal plugin 2 1.0 .................. SKIPPED
[INFO] Metrics portal plugin 1.1 .......................... SKIPPED
[INFO] Performance Mining Service 1.0 ..................... SKIPPED
[INFO] Performance Mining portal plugin 1.0 ............... SKIPPED
[INFO] Predictive monitor logic 1.0 ....................... SKIPPED
[INFO] Predictive monitor portal plugin 1.0 ............... SKIPPED
[INFO] Predictor training portal plugin 1.0 ............... SKIPPED
[INFO] PQL Indexer portal plugin 1.1 ...................... SKIPPED
[INFO] PQL portal plugin 1.1 .............................. SKIPPED
[INFO] Process drift detection service 1.1 ................ SKIPPED
[INFO] Process drift detection portal plugin 1.1 .......... SKIPPED
[INFO] Quaestio 1.0 ....................................... SKIPPED
[INFO] Quaestio portal plugin 1.1 ......................... SKIPPED
[INFO] Stage Mining Service 1.1 ........................... SKIPPED
[INFO] Stage Mining Portal plugin 1.1 ..................... SKIPPED
[INFO] Process Discoverer Logic 2.0.0 ..................... SKIPPED
[INFO] Process Discoverer Portal Plugin 2.0.0 ............. SKIPPED
[INFO] XES selection portal plugin 1.0 .................... SKIPPED
[INFO] UI theme selection portal plugin 1.0 ............... SKIPPED
[INFO] pql-bot 1.2 ........................................ SKIPPED
[INFO] Stencilset Compressor 1.1 .......................... SKIPPED
[INFO] Apromore Editor Extension: Downloader 1.2 .......... SKIPPED
[INFO] Apromore Editor Extension: EPC 1.2 ................. SKIPPED
[INFO] Apromore Editor Extension: JPDL 1.2 ................ SKIPPED
[INFO] Apromore Editor Extension: PDF 1.2 ................. SKIPPED
[INFO] Apromore Editor Extension: Petri Net 1.2 ........... SKIPPED
[INFO] Apromore Editor Extension: Syntax Checker 1.2 ...... SKIPPED
[INFO] Apromore Editor Extension: XPDL 1.2 ................ SKIPPED
[INFO] Apromore Editor Extension: YAWL 1.2 ................ SKIPPED
[INFO] Apromore Editor 1.2 ................................ SKIPPED
[INFO] Apromore File Store 1.1 ............................ SKIPPED
[INFO] Apromore Manager Web Services 1.1 .................. SKIPPED
[INFO] Apromore PQL Indexer 1.1 ........................... SKIPPED
[INFO] Apromore BPMN Editor 1.1 ........................... SKIPPED
[INFO] Apromore Editor Bundle Assembly 1.1 ................ SKIPPED
[INFO] Apromore File Store Bundle Assembly 1.1 ............ SKIPPED
[INFO] Apromore Manager Bundle Assembly 1.1 ............... SKIPPED
[INFO] Apromore Portal Bundle Assembly 1.1 ................ SKIPPED
[INFO] Apromore PQL Indexer Bundle Assembly 1.1 ........... SKIPPED
[INFO] Predictive Monitor Bundle Assembly 1.1 ............. SKIPPED
[INFO] Apromore Custom Plugins Assembly 1.1 ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:47 min
[INFO] Finished at: 2020-01-31T10:41:29+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.1:revision (get-the-git-infos) on project anf-schema: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
[ERROR]

Can you help me?

**Environment**
os
Windows 10

java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\DevEnv\apache-maven-3.6.3\bin\..
Java version: 1.8.0_241, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_241\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

ant -version
Apache Ant(TM) version 1.10.7 compiled on September 1 2019

**Comment by raboczi** [comment]
We're in the process of rearranging the build process so that the open source version of Apromore is built from a new repository named ApromoreCE rather than ApromoreCore.  The error you're seeing is a bit a code that slipped through that references the not-yet-public ApromoreCE.

The best suggestion I can give for now is to check out the v7.12 branch; I'm pretty sure that version of ApromoreCore can still be built independently.

**Comment by ffalcolini** [comment]
Thank you for your suggestion.
I managed to install Apromore. Now it works!

I noticed though that I can't import csv.
That is, if I use the File -> Upload function, I can import XES files, but not CSV files.
Could you help me understand why I can't import CSV?

Thanks a lot!
